### ISSUE TITLE
Always on display not working?

### ISSUE THREAD

**Issue by preetangad** [yoosee/FitBitWatchObsidian#3]
Hey I love this watchface and I'm trying to use it on my Versa 2. I see that there is a setting for Display Always On and I have enabled it but it doesn't seem to have any effect. I love this clock face but always on display would make it my default. Color customization would be awesome too but not essential.

**Comment by yoosee** [comment]
Thank you for leaving the comment. "AlwaysOn" is a flag exists on the SDK but seems not available or effective unless Fitbit grants special permission to developer account, which I don't have.
https://community.fitbit.com/t5/SDK-Development/Always-on-Display-review-process/td-p/3995922
