### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by DN64** [yoosee/FitBitWatchObsidian#4]
The date only has 1 spot past 9 it only shows the dirt digit.

**Comment by yoosee** [comment]
it seems to be broken by Versa SDK side changes. I adjusted width a bit wider and it seems working on my Versa now.
Watchface will be updated in the store.

**Comment by DN64** [comment]
I just reinstalled it and same issue
Today is the 16th  [cid:F1987BB7-E230-4C9A-870F-FEE7FF75E83A-L0-001]

Sent from Dales iPhone

On Mar 15, 2021, at 11:13 PM, Yoshinori Ikarashi ***@***.***> wrote:

﻿

Closed #4<https://github.com/yoosee/FitBitWatchObsidian/issues/4>.

**Comment by yoosee** [comment]
Updated version is still under review, not yet published in Fitbit Gallery. It usually took less than a day but not sure.

**Comment by yoosee** [comment]
Publish rejected/postponed due to some misconfiguration in build target. I'm going to fix it and re-submit. Please wait for a while...

**Comment by yoosee** [comment]
Review finished (took 6 days since submitted) and published now. It works well on my Versa.

**Comment by DN64** [comment]
Looks good. Thanks

Sent from Dales iPhone

On Mar 23, 2021, at 7:16 AM, Yoshinori Ikarashi ***@***.***> wrote:

﻿

Review finished (took 6 days since submitted) and published now. It works well on my Versa.
